// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbBbBHHqCJwFn-A97TrqjO18qJISfvG0c',
    appId: '1:239775100406:web:35b24d70327c6695302bd7',
    messagingSenderId: '239775100406',
    projectId: 'news-app-992ae',
    authDomain: 'news-app-992ae.firebaseapp.com',
    storageBucket: 'news-app-992ae.firebasestorage.app',
    measurementId: 'G-4HF395KNYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhKwIKgCX_5UNAQEZ7-DFyYLFTwDjUVW0',
    appId: '1:239775100406:android:a498e3c0bf4bc41c302bd7',
    messagingSenderId: '239775100406',
    projectId: 'news-app-992ae',
    storageBucket: 'news-app-992ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo9v8kDyGISHfGw8GvvrNp3PjfEKpjyKA',
    appId: '1:239775100406:ios:a96ee218f74aaad4302bd7',
    messagingSenderId: '239775100406',
    projectId: 'news-app-992ae',
    storageBucket: 'news-app-992ae.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo9v8kDyGISHfGw8GvvrNp3PjfEKpjyKA',
    appId: '1:239775100406:ios:a96ee218f74aaad4302bd7',
    messagingSenderId: '239775100406',
    projectId: 'news-app-992ae',
    storageBucket: 'news-app-992ae.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbBbBHHqCJwFn-A97TrqjO18qJISfvG0c',
    appId: '1:239775100406:web:d75a01ee1e24f537302bd7',
    messagingSenderId: '239775100406',
    projectId: 'news-app-992ae',
    authDomain: 'news-app-992ae.firebaseapp.com',
    storageBucket: 'news-app-992ae.firebasestorage.app',
    measurementId: 'G-GZSZ24D4VK',
  );
}
